export default [
  {
    id: 1,
    title: "Phase 1: Foundation",
    subtitle: "Lessons 1-20",
    slug: "phase-1",
    lessonRange: "1-20",
    description: "The math journey begins here. Phase 1 introduces numbers 0-10, counting, one-to-one correspondence, and number recognition.",
    conceptsIntroduced: [
      { symbol: "0", lesson: 1, type: "number", example: "zero, nothing" },
      { symbol: "1", lesson: 1, type: "number", example: "one, single" },
      { symbol: "2", lesson: 2, type: "number", example: "two, pair" },
      { symbol: "3", lesson: 3, type: "number", example: "three" },
      { symbol: "=", lesson: 4, type: "symbol", example: "equals, is the same as" },
      { symbol: "4", lesson: 5, type: "number", example: "four" },
      { symbol: "5", lesson: 7, type: "number", example: "five" },
      { symbol: "6", lesson: 9, type: "number", example: "six" },
      { symbol: "7", lesson: 11, type: "number", example: "seven" },
      { symbol: "8", lesson: 13, type: "number", example: "eight" },
      { symbol: "9", lesson: 15, type: "number", example: "nine" },
      { symbol: "10", lesson: 17, type: "number", example: "ten" },
      { symbol: ">", lesson: 18, type: "symbol", example: "greater than" },
      { symbol: "<", lesson: 18, type: "symbol", example: "less than" },
    ],
    skills: [
      "Recognizing and naming numbers 0-10",
      "Counting objects with one-to-one correspondence",
      "Writing numerals 0-10",
      "Comparing numbers (more, less, equal)",
      "Ordering numbers from least to greatest",
    ],
    tips: "Go slowly. The learner is building number sense \u2014 the ability to understand what numbers mean, not just recite them. Use physical objects (fingers, blocks, dots) alongside the screen. Each lesson should take 5\u201310 minutes.",
    whatToExpect: "By the end of Phase 1, the learner will recognize all numbers 0\u201310, count objects accurately, and understand basic comparisons (more/less/equal).",
  },
  {
    id: 2,
    title: "Phase 2: Counting & Comparing",
    subtitle: "Lessons 21-40",
    slug: "phase-2",
    lessonRange: "21-40",
    description: "Phase 2 extends counting to 20, introduces number patterns, and builds fluency with number order and comparisons.",
    conceptsIntroduced: [
      { symbol: "11-15", lesson: 21, type: "number range", example: "eleven through fifteen" },
      { symbol: "16-20", lesson: 26, type: "number range", example: "sixteen through twenty" },
      { symbol: "+", lesson: 31, type: "symbol", example: "plus, add" },
      { symbol: "number line", lesson: 33, type: "tool", example: "0 to 20 number line" },
    ],
    skills: [
      "Counting to 20 fluently",
      "Counting backward from 10",
      "Identifying numbers 11-20",
      "Understanding 'one more' and 'one less'",
      "Introduction to the plus symbol",
    ],
    tips: "The teen numbers (11\u201319) are notoriously confusing. 'Thirteen' does not obviously connect to '3' and '10'. Spend extra time here. Use tally marks and dot patterns to make it concrete.",
    whatToExpect: "By the end of Phase 2, the learner counts to 20, understands number order, and is ready to begin addition.",
  },
  {
    id: 3,
    title: "Phase 3: Addition",
    subtitle: "Lessons 41-65",
    slug: "phase-3",
    lessonRange: "41-65",
    description: "Phase 3 teaches addition facts to 10 systematically, starting with +1, +2, then building to all single-digit addition.",
    conceptsIntroduced: [
      { symbol: "+1", lesson: 41, type: "operation", example: "3 + 1 = 4" },
      { symbol: "+2", lesson: 45, type: "operation", example: "5 + 2 = 7" },
      { symbol: "+3", lesson: 49, type: "operation", example: "4 + 3 = 7" },
      { symbol: "doubles", lesson: 53, type: "strategy", example: "3 + 3 = 6" },
      { symbol: "+0", lesson: 56, type: "operation", example: "5 + 0 = 5" },
      { symbol: "commutative", lesson: 58, type: "property", example: "2 + 3 = 3 + 2" },
      { symbol: "number bonds", lesson: 60, type: "concept", example: "5 = 2 + 3" },
    ],
    skills: [
      "Adding 1, 2, and 3 to any single digit",
      "Doubles facts (1+1 through 5+5)",
      "Adding zero",
      "Understanding the commutative property",
      "Number bonds to 10",
      "Solving addition equations with missing addends",
    ],
    tips: "Addition is taught in a specific order for a reason. +1 facts are easiest because they connect to counting. Doubles are memorable. Build from what the child already knows. Do not rush to subtraction.",
    whatToExpect: "By the end of Phase 3, the learner knows all addition facts to 10 and understands number bonds.",
  },
  {
    id: 4,
    title: "Phase 4: Subtraction",
    subtitle: "Lessons 66-85",
    slug: "phase-4",
    lessonRange: "66-85",
    description: "Phase 4 introduces subtraction as 'taking away' and builds the connection between addition and subtraction.",
    conceptsIntroduced: [
      { symbol: "\u2212", lesson: 66, type: "symbol", example: "minus, take away" },
      { symbol: "\u22121", lesson: 66, type: "operation", example: "5 \u2212 1 = 4" },
      { symbol: "\u22122", lesson: 70, type: "operation", example: "7 \u2212 2 = 5" },
      { symbol: "\u22123", lesson: 74, type: "operation", example: "8 \u2212 3 = 5" },
      { symbol: "fact families", lesson: 78, type: "concept", example: "3+4=7, 4+3=7, 7\u22123=4, 7\u22124=3" },
      { symbol: "\u22120", lesson: 80, type: "operation", example: "5 \u2212 0 = 5" },
    ],
    skills: [
      "Subtracting 1, 2, and 3 from numbers to 10",
      "Understanding subtraction as 'taking away'",
      "Connecting subtraction to addition (fact families)",
      "Subtracting zero",
      "Solving subtraction equations with missing numbers",
    ],
    tips: "Teach subtraction explicitly as the inverse of addition. If the child knows 3 + 4 = 7, they can figure out 7 \u2212 3 = 4. Fact families are the bridge between the two operations.",
    whatToExpect: "By the end of Phase 4, the learner knows all subtraction facts to 10 and understands the relationship between addition and subtraction.",
  },
  {
    id: 5,
    title: "Phase 5: Place Value",
    subtitle: "Lessons 86-105",
    slug: "phase-5",
    lessonRange: "86-105",
    description: "Phase 5 introduces place value (tens and ones), counting to 100, and addition/subtraction within 20.",
    conceptsIntroduced: [
      { symbol: "tens", lesson: 86, type: "place value", example: "10 = 1 ten, 0 ones" },
      { symbol: "ones", lesson: 86, type: "place value", example: "13 = 1 ten, 3 ones" },
      { symbol: "counting to 50", lesson: 90, type: "number range", example: "twenty-one through fifty" },
      { symbol: "counting to 100", lesson: 95, type: "number range", example: "fifty-one through one hundred" },
      { symbol: "addition to 20", lesson: 100, type: "operation", example: "8 + 7 = 15" },
    ],
    skills: [
      "Understanding tens and ones",
      "Representing two-digit numbers with place value",
      "Counting to 100 by ones and tens",
      "Skip counting by 2s, 5s, and 10s",
      "Adding and subtracting within 20",
    ],
    tips: "Place value is the single most important concept in elementary math. Use base-ten blocks or draw tens/ones diagrams. If the child does not understand that 23 means '2 tens and 3 ones', stop and reteach.",
    whatToExpect: "By the end of Phase 5, the learner understands place value, counts to 100, and can add/subtract within 20.",
  },
  {
    id: 6,
    title: "Phase 6: Fluency",
    subtitle: "Lessons 106-125",
    slug: "phase-6",
    lessonRange: "106-125",
    description: "Phase 6 builds fluency with addition and subtraction facts to 20, introduces mental math strategies, and begins two-digit addition.",
    conceptsIntroduced: [
      { symbol: "make 10", lesson: 106, type: "strategy", example: "8 + 5 = 8 + 2 + 3 = 10 + 3 = 13" },
      { symbol: "doubles +1", lesson: 110, type: "strategy", example: "6 + 7 = 6 + 6 + 1 = 13" },
      { symbol: "two-digit + one-digit", lesson: 115, type: "operation", example: "24 + 5 = 29" },
      { symbol: "two-digit + tens", lesson: 120, type: "operation", example: "35 + 20 = 55" },
    ],
    skills: [
      "Rapid recall of addition/subtraction facts to 20",
      "Make-10 strategy",
      "Doubles-plus-one strategy",
      "Adding a one-digit number to a two-digit number",
      "Adding multiples of 10 to two-digit numbers",
    ],
    tips: "Fluency means speed AND accuracy. Use timed practice sparingly \u2014 the goal is automaticity, not anxiety. The 'make 10' strategy is powerful and will serve the child for years.",
    whatToExpect: "By the end of Phase 6, the learner has rapid recall of facts to 20 and can do simple two-digit addition.",
  },
  {
    id: 7,
    title: "Phase 7: Mastery",
    subtitle: "Lessons 126-150",
    slug: "phase-7",
    lessonRange: "126-150",
    description: "Phase 7 covers two-digit addition and subtraction (with and without regrouping), word problems, and mixed practice for complete mastery.",
    conceptsIntroduced: [
      { symbol: "two-digit + two-digit", lesson: 126, type: "operation", example: "34 + 25 = 59" },
      { symbol: "regrouping (carrying)", lesson: 130, type: "concept", example: "28 + 15 = 43" },
      { symbol: "two-digit \u2212 two-digit", lesson: 135, type: "operation", example: "56 \u2212 23 = 33" },
      { symbol: "regrouping (borrowing)", lesson: 140, type: "concept", example: "42 \u2212 17 = 25" },
      { symbol: "word problems", lesson: 145, type: "application", example: "Sam has 12 apples. He gives away 5. How many are left?" },
    ],
    skills: [
      "Two-digit addition without regrouping",
      "Two-digit addition with regrouping (carrying)",
      "Two-digit subtraction without regrouping",
      "Two-digit subtraction with regrouping (borrowing)",
      "Solving addition and subtraction word problems",
      "Mixed practice with all four types",
    ],
    tips: "The child is now doing real arithmetic. Regrouping (carrying and borrowing) is the hardest concept in this entire program. Use place value charts and base-ten block drawings. Do not rush.",
    whatToExpect: "By the end of Phase 7, the learner has completed the full K\u20134 math foundations curriculum. They can add and subtract two-digit numbers, solve word problems, and have automatic recall of basic facts.",
  },
];
